// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fusegit.proto

package fg_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CheckoutRequest struct {
	RevisionHash         string   `protobuf:"bytes,1,opt,name=revision_hash,json=revisionHash,proto3" json:"revision_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckoutRequest) Reset()         { *m = CheckoutRequest{} }
func (m *CheckoutRequest) String() string { return proto.CompactTextString(m) }
func (*CheckoutRequest) ProtoMessage()    {}
func (*CheckoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47e6e4b3212236eb, []int{0}
}

func (m *CheckoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckoutRequest.Unmarshal(m, b)
}
func (m *CheckoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckoutRequest.Marshal(b, m, deterministic)
}
func (m *CheckoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckoutRequest.Merge(m, src)
}
func (m *CheckoutRequest) XXX_Size() int {
	return xxx_messageInfo_CheckoutRequest.Size(m)
}
func (m *CheckoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckoutRequest proto.InternalMessageInfo

func (m *CheckoutRequest) GetRevisionHash() string {
	if m != nil {
		return m.RevisionHash
	}
	return ""
}

type CheckoutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckoutResponse) Reset()         { *m = CheckoutResponse{} }
func (m *CheckoutResponse) String() string { return proto.CompactTextString(m) }
func (*CheckoutResponse) ProtoMessage()    {}
func (*CheckoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47e6e4b3212236eb, []int{1}
}

func (m *CheckoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckoutResponse.Unmarshal(m, b)
}
func (m *CheckoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckoutResponse.Marshal(b, m, deterministic)
}
func (m *CheckoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckoutResponse.Merge(m, src)
}
func (m *CheckoutResponse) XXX_Size() int {
	return xxx_messageInfo_CheckoutResponse.Size(m)
}
func (m *CheckoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckoutResponse proto.InternalMessageInfo

type FetchRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchRequest) Reset()         { *m = FetchRequest{} }
func (m *FetchRequest) String() string { return proto.CompactTextString(m) }
func (*FetchRequest) ProtoMessage()    {}
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47e6e4b3212236eb, []int{2}
}

func (m *FetchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchRequest.Unmarshal(m, b)
}
func (m *FetchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchRequest.Marshal(b, m, deterministic)
}
func (m *FetchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchRequest.Merge(m, src)
}
func (m *FetchRequest) XXX_Size() int {
	return xxx_messageInfo_FetchRequest.Size(m)
}
func (m *FetchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchRequest proto.InternalMessageInfo

type FetchResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchResponse) Reset()         { *m = FetchResponse{} }
func (m *FetchResponse) String() string { return proto.CompactTextString(m) }
func (*FetchResponse) ProtoMessage()    {}
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47e6e4b3212236eb, []int{3}
}

func (m *FetchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchResponse.Unmarshal(m, b)
}
func (m *FetchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchResponse.Marshal(b, m, deterministic)
}
func (m *FetchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchResponse.Merge(m, src)
}
func (m *FetchResponse) XXX_Size() int {
	return xxx_messageInfo_FetchResponse.Size(m)
}
func (m *FetchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchResponse proto.InternalMessageInfo

type LogRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogRequest) Reset()         { *m = LogRequest{} }
func (m *LogRequest) String() string { return proto.CompactTextString(m) }
func (*LogRequest) ProtoMessage()    {}
func (*LogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47e6e4b3212236eb, []int{4}
}

func (m *LogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogRequest.Unmarshal(m, b)
}
func (m *LogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogRequest.Marshal(b, m, deterministic)
}
func (m *LogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogRequest.Merge(m, src)
}
func (m *LogRequest) XXX_Size() int {
	return xxx_messageInfo_LogRequest.Size(m)
}
func (m *LogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogRequest proto.InternalMessageInfo

type LogResponse struct {
	RevisionHashes       []string `protobuf:"bytes,1,rep,name=revision_hashes,json=revisionHashes,proto3" json:"revision_hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogResponse) Reset()         { *m = LogResponse{} }
func (m *LogResponse) String() string { return proto.CompactTextString(m) }
func (*LogResponse) ProtoMessage()    {}
func (*LogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47e6e4b3212236eb, []int{5}
}

func (m *LogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogResponse.Unmarshal(m, b)
}
func (m *LogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogResponse.Marshal(b, m, deterministic)
}
func (m *LogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogResponse.Merge(m, src)
}
func (m *LogResponse) XXX_Size() int {
	return xxx_messageInfo_LogResponse.Size(m)
}
func (m *LogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogResponse proto.InternalMessageInfo

func (m *LogResponse) GetRevisionHashes() []string {
	if m != nil {
		return m.RevisionHashes
	}
	return nil
}

type StatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_47e6e4b3212236eb, []int{6}
}

func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (m *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(m, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

type StatusResponse struct {
	RevisionHash         string   `protobuf:"bytes,1,opt,name=revision_hash,json=revisionHash,proto3" json:"revision_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_47e6e4b3212236eb, []int{7}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetRevisionHash() string {
	if m != nil {
		return m.RevisionHash
	}
	return ""
}

func init() {
	proto.RegisterType((*CheckoutRequest)(nil), "fg_proto.CheckoutRequest")
	proto.RegisterType((*CheckoutResponse)(nil), "fg_proto.CheckoutResponse")
	proto.RegisterType((*FetchRequest)(nil), "fg_proto.FetchRequest")
	proto.RegisterType((*FetchResponse)(nil), "fg_proto.FetchResponse")
	proto.RegisterType((*LogRequest)(nil), "fg_proto.LogRequest")
	proto.RegisterType((*LogResponse)(nil), "fg_proto.LogResponse")
	proto.RegisterType((*StatusRequest)(nil), "fg_proto.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "fg_proto.StatusResponse")
}

func init() {
	proto.RegisterFile("fusegit.proto", fileDescriptor_47e6e4b3212236eb)
}

var fileDescriptor_47e6e4b3212236eb = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x50, 0x4b, 0x4f, 0xc2, 0x40,
	0x10, 0xb6, 0x21, 0x22, 0x8c, 0x7d, 0x98, 0x89, 0x8f, 0xba, 0x27, 0x52, 0x0f, 0x72, 0xea, 0xc1,
	0x07, 0x07, 0x13, 0x4f, 0x24, 0xc4, 0x03, 0xa7, 0xfa, 0x03, 0x48, 0x25, 0x43, 0xb7, 0x31, 0x61,
	0x91, 0xd9, 0xfa, 0xf7, 0x35, 0xb6, 0xbb, 0x6c, 0xa1, 0x1e, 0xb8, 0xed, 0x7e, 0xaf, 0xc9, 0xf7,
	0x41, 0xb0, 0xaa, 0x98, 0x8a, 0x52, 0xa7, 0x9b, 0xad, 0xd2, 0x0a, 0x07, 0xab, 0x62, 0x51, 0xbf,
	0x92, 0x09, 0x44, 0x53, 0x49, 0xcb, 0x4f, 0x55, 0xe9, 0x8c, 0xbe, 0x2a, 0x62, 0x8d, 0x77, 0x10,
	0x6c, 0xe9, 0xbb, 0xe4, 0x52, 0xad, 0x17, 0x32, 0x67, 0x19, 0x7b, 0x23, 0x6f, 0x3c, 0xcc, 0x7c,
	0x0b, 0xbe, 0xe5, 0x2c, 0x13, 0x84, 0x0b, 0xe7, 0xe3, 0x8d, 0x5a, 0x33, 0x25, 0x21, 0xf8, 0x33,
	0xd2, 0x4b, 0x69, 0x82, 0x92, 0x08, 0x02, 0xf3, 0x37, 0x02, 0x1f, 0x60, 0xae, 0x0a, 0x4b, 0x4f,
	0xe0, 0xbc, 0xfe, 0x35, 0x24, 0xde, 0x43, 0xb4, 0x77, 0x96, 0x38, 0xf6, 0x46, 0xbd, 0xf1, 0x30,
	0x0b, 0xdb, 0x87, 0x89, 0xff, 0x62, 0xdf, 0x75, 0xae, 0x2b, 0xb6, 0x41, 0xcf, 0x10, 0x5a, 0xc0,
	0x64, 0x1d, 0x53, 0xe1, 0xe1, 0xc7, 0x83, 0xb3, 0x59, 0x33, 0x0b, 0x4e, 0x61, 0x60, 0xeb, 0xe0,
	0x6d, 0x6a, 0xd7, 0x49, 0x0f, 0xa6, 0x11, 0xe2, 0x3f, 0xca, 0x94, 0x3b, 0xc1, 0x17, 0x38, 0xad,
	0xfb, 0xe2, 0xb5, 0x93, 0xb5, 0x07, 0x11, 0x37, 0x1d, 0x7c, 0xe7, 0x7d, 0x82, 0xde, 0x5c, 0x15,
	0x78, 0xe9, 0x14, 0x6e, 0x29, 0x71, 0x75, 0x80, 0xee, 0x5c, 0xaf, 0xd0, 0x6f, 0x9a, 0x63, 0x2b,
	0x7a, 0x6f, 0x1c, 0x11, 0x77, 0x09, 0x6b, 0xff, 0xe8, 0xd7, 0xf8, 0xe3, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x7c, 0xf0, 0x68, 0x8d, 0x1e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FusegitClient is the client API for Fusegit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FusegitClient interface {
	Checkout(ctx context.Context, in *CheckoutRequest, opts ...grpc.CallOption) (*CheckoutResponse, error)
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error)
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type fusegitClient struct {
	cc grpc.ClientConnInterface
}

func NewFusegitClient(cc grpc.ClientConnInterface) FusegitClient {
	return &fusegitClient{cc}
}

func (c *fusegitClient) Checkout(ctx context.Context, in *CheckoutRequest, opts ...grpc.CallOption) (*CheckoutResponse, error) {
	out := new(CheckoutResponse)
	err := c.cc.Invoke(ctx, "/fg_proto.Fusegit/Checkout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fusegitClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error) {
	out := new(FetchResponse)
	err := c.cc.Invoke(ctx, "/fg_proto.Fusegit/Fetch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fusegitClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, "/fg_proto.Fusegit/Log", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fusegitClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/fg_proto.Fusegit/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FusegitServer is the server API for Fusegit service.
type FusegitServer interface {
	Checkout(context.Context, *CheckoutRequest) (*CheckoutResponse, error)
	Fetch(context.Context, *FetchRequest) (*FetchResponse, error)
	Log(context.Context, *LogRequest) (*LogResponse, error)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
}

// UnimplementedFusegitServer can be embedded to have forward compatible implementations.
type UnimplementedFusegitServer struct {
}

func (*UnimplementedFusegitServer) Checkout(ctx context.Context, req *CheckoutRequest) (*CheckoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Checkout not implemented")
}
func (*UnimplementedFusegitServer) Fetch(ctx context.Context, req *FetchRequest) (*FetchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fetch not implemented")
}
func (*UnimplementedFusegitServer) Log(ctx context.Context, req *LogRequest) (*LogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Log not implemented")
}
func (*UnimplementedFusegitServer) Status(ctx context.Context, req *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}

func RegisterFusegitServer(s *grpc.Server, srv FusegitServer) {
	s.RegisterService(&_Fusegit_serviceDesc, srv)
}

func _Fusegit_Checkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FusegitServer).Checkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fg_proto.Fusegit/Checkout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FusegitServer).Checkout(ctx, req.(*CheckoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fusegit_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FusegitServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fg_proto.Fusegit/Fetch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FusegitServer).Fetch(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fusegit_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FusegitServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fg_proto.Fusegit/Log",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FusegitServer).Log(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fusegit_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FusegitServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fg_proto.Fusegit/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FusegitServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Fusegit_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fg_proto.Fusegit",
	HandlerType: (*FusegitServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Checkout",
			Handler:    _Fusegit_Checkout_Handler,
		},
		{
			MethodName: "Fetch",
			Handler:    _Fusegit_Fetch_Handler,
		},
		{
			MethodName: "Log",
			Handler:    _Fusegit_Log_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Fusegit_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fusegit.proto",
}
